---
- name: Install and start Nginx
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest


    - name: Start Nginx service
      service:
        name: nginx
        state: started
